// VoiceGallery.jsx — two zones:
//   • Archetypes — a browsable library of *designed* voices (no real people),
//     generated by VoiceStudio's own voice-design engine. Featured cards up top,
//     facet filters to explore hundreds. (core.archetypes / /archetypes API)
//   • My Imports — a neutral importer: paste any URL you have the rights to, or
//     upload a file, trim it, save it. The project ships no celebrity catalog.
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Sparkles, Store, Upload } from 'lucide-react';
import { Segmented } from '../ui';
import { archetypePreviewUrl, useArchetypeAsProfile } from '../api/archetypes';
import { addCommunityItem, communityPreviewUrl } from '../api/community';
import { previewVoiceUrl } from '../api/gallery';
import { useAppStore } from '../store';
import { apiFetch } from '../api/client';
import { playBlobAudio } from '../utils/media';
import { stopActivePlayback } from '../utils/playback';
import { nextCastColor } from '../utils/storyCast';
import { instructToVdStates } from '../utils/voiceInstruct';
import ArchetypesZone from '../components/gallery/ArchetypesZone';
import CommunityZone from '../components/gallery/CommunityZone';
import ImportsZone from '../components/gallery/ImportsZone';

const NOOP = () => {};

export default function VoiceGallery({ clearSelectedProfile = NOOP }) {
  const { t } = useTranslation();

  const zone = useAppStore((s) => s.galleryZone);
  const setZone = useAppStore((s) => s.setGalleryZone);
  const filters = useAppStore((s) => s.archetypeFilters);
  const setFilter = useAppStore((s) => s.setArchetypeFilter);
  const resetFilters = useAppStore((s) => s.resetArchetypeFilters);
  const favorites = useAppStore((s) => s.favoriteArchetypeIds);
  const toggleFavorite = useAppStore((s) => s.toggleFavoriteArchetype);
  const viewMode = useAppStore((s) => s.galleryViewMode);
  const setViewMode = useAppStore((s) => s.setGalleryViewMode);
  const setMode = useAppStore((s) => s.setMode);
  const setDefineMethod = useAppStore((s) => s.setDefineMethod);
  const setPendingProfileId = useAppStore((s) => s.setPendingProfileId);
  const setInstruct = useAppStore((s) => s.setInstruct);
  const setVdStates = useAppStore((s) => s.setVdStates);
  const setLanguage = useAppStore((s) => s.setLanguage);
  const upsertCastMember = useAppStore((s) => s.upsertCastMember);
  const setOutputPrefs = useAppStore((s) => s.setOutputPrefs);
  const convertMode = useAppStore((s) => s.convertMode);

  const [playingId, setPlayingId] = useState(null);
  const [loadingPreviewId, setLoadingPreviewId] = useState(null);
  const [materializingId, setMaterializingId] = useState(null);
  const [notice, setNotice] = useState(null);
  const noticeTimer = useRef(null);
  const materializingRef = useRef(false);
  // Stale-async guards: gallery operations can outlive their trigger — a
  // preview fetch resolving after the page unmounted, a decode-error retry
  // firing after the user picked another voice, or a save-as-profile finishing
  // after the user left (which would redirect them into a workspace they had
  // already navigated away from). Each async operation captures the current
  // generation token and re-checks it before playback, navigation, and every
  // setState; unmount and each newer operation of the same kind invalidate it.
  const previewSeq = useRef(0);
  const materializeSeq = useRef(0);

  const flash = useCallback((msg) => {
    setNotice(msg);
    if (noticeTimer.current) window.clearTimeout(noticeTimer.current);
    noticeTimer.current = window.setTimeout(() => setNotice(null), 3500);
  }, []);

  useEffect(
    () => () => {
      previewSeq.current += 1;
      materializeSeq.current += 1;
      if (noticeTimer.current) window.clearTimeout(noticeTimer.current);
    },
    [],
  );

  // Fetch a preview clip and play it through the shared playback path
  // (playBlobAudio handles the Tauri "blob: URLs are dead in media elements"
  // detour — this page used to carry its own copy of that logic). The claim
  // routes to the global mini-player with the voice name as its label, and
  // starting any other playback stops this one (#316).
  const playUrl = useCallback(
    async (url, id, label, fallbackUrl = null) => {
      if (playingId === id) {
        stopActivePlayback(); // onDone('stopped') below resets playingId
        return;
      }
      const gen = ++previewSeq.current;
      const stale = () => previewSeq.current !== gen;
      setLoadingPreviewId(id);
      try {
        // no-store: preview audio is re-rendered server-side when an archetype is
        // fixed/changed, but the URL is stable. Without this the WebView's HTTP
        // cache replays the first clip it ever fetched (a stale render) forever.
        const resp = await apiFetch(url, { cache: 'no-store' });
        const blob = await resp.blob();
        if (stale()) return;
        setPlayingId(id);
        await playBlobAudio(blob, {
          label,
          // A present, verified gallery file can still be undecodable. The media
          // element reports that asynchronously, so retry from the backend's
          // explicit local-render path here rather than leaving a silent card.
          onDone: (reason) => {
            if (stale()) return;
            setPlayingId((cur) => (cur === id ? null : cur));
            if (reason === 'error' && fallbackUrl) {
              void playUrl(fallbackUrl, id, label);
            }
          },
        });
      } catch (e) {
        if (stale()) return;
        setPlayingId((cur) => (cur === id ? null : cur));
        flash(
          t('gallery.preview_failed', {
            message: e?.message || String(e),
            defaultValue: 'Preview unavailable: {{message}}',
          }),
        );
      } finally {
        if (!stale()) setLoadingPreviewId(null);
      }
    },
    [flash, playingId, t],
  );

  const openDesigner = useCallback(
    (item) => {
      clearSelectedProfile();
      setPendingProfileId(null);
      setVdStates(instructToVdStates(item.instruct || ''));
      setInstruct('');
      setLanguage(item.language || 'Auto');
      setDefineMethod('design');
      setMode('studio');
    },
    [
      clearSelectedProfile,
      setDefineMethod,
      setInstruct,
      setLanguage,
      setMode,
      setPendingProfileId,
      setVdStates,
    ],
  );

  const placeProfile = useCallback(
    (profile, target = 'studio') => {
      if (target === 'studio') {
        clearSelectedProfile();
        setPendingProfileId(profile.profile_id);
        setMode('studio');
        return;
      }
      if (target === 'stories') {
        const cast = useAppStore.getState().cast || [];
        if (!cast.some((member) => member.profileId === profile.profile_id)) {
          upsertCastMember({
            id: `voice_${profile.profile_id}`,
            name: profile.name,
            color: nextCastColor(cast),
            profileId: profile.profile_id,
          });
        }
        convertMode('stories');
        setMode('stories');
        return;
      }
      setOutputPrefs({ defaultVoice: profile.profile_id });
      convertMode('audiobook');
      setMode('audiobook');
    },
    [
      clearSelectedProfile,
      convertMode,
      setMode,
      setOutputPrefs,
      setPendingProfileId,
      upsertCastMember,
    ],
  );

  const materialize = useCallback(
    async (item, createProfile, target) => {
      // A ref closes the double-click window before React can paint `disabled`.
      if (materializingRef.current) return;
      materializingRef.current = true;
      const gen = ++materializeSeq.current;
      const stale = () => materializeSeq.current !== gen;
      setMaterializingId(item.id);
      try {
        const profile = await createProfile(item.id, item.name);
        if (stale()) return;
        placeProfile(profile, target);
      } catch (e) {
        if (stale()) return;
        flash(
          t('gallery.use_failed', {
            message: e?.message || String(e),
            defaultValue: 'Could not create that voice: {{message}}',
          }),
        );
      } finally {
        materializingRef.current = false;
        if (!stale()) setMaterializingId(null);
      }
    },
    [flash, placeProfile, t],
  );

  const communityPlaybackId = (item) =>
    `community:${item._source_repo || item.source || 'default'}:${item.id}`;

  const zoneItems = [
    {
      value: 'archetypes',
      label: (
        <span className="inline-flex items-center gap-[5px]">
          <Sparkles size={14} /> {t('gallery.zone_archetypes', { defaultValue: 'Archetypes' })}
        </span>
      ),
    },
    {
      value: 'community',
      label: (
        <span className="inline-flex items-center gap-[5px]">
          <Store size={14} /> {t('gallery.zone_community', { defaultValue: 'Community' })}
        </span>
      ),
    },
    {
      value: 'imports',
      label: (
        <span className="inline-flex items-center gap-[5px]">
          <Upload size={14} /> {t('gallery.zone_imports', { defaultValue: 'My Imports' })}
        </span>
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-[12px] p-[12px] h-full overflow-hidden">
      <div className="shrink-0">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-[1.1rem] font-semibold m-0 text-[var(--text-primary)]">
              {t('gallery.title', { defaultValue: 'VoiceStudio Gallery' })}
            </h2>
            <p className="mt-[2px] mr-0 mb-0 ml-0 text-[0.72rem] text-[var(--text-secondary)]">
              {t('gallery.subtitle', {
                defaultValue: 'Hundreds of ready-made designed voices — pick one and go.',
              })}
            </p>
          </div>
          <Segmented items={zoneItems} value={zone} onChange={setZone} />
        </div>
      </div>

      {notice && (
        <div className="shrink-0 px-[10px] py-[7px] bg-bg-elev-2 border-l-[3px] border-l-[color:var(--accent)] rounded-[6px] text-[0.75rem] text-[var(--text-primary)]">
          {notice}
        </div>
      )}

      {zone === 'archetypes' ? (
        <ArchetypesZone
          t={t}
          filters={filters}
          setFilter={setFilter}
          resetFilters={resetFilters}
          favorites={favorites}
          toggleFavorite={toggleFavorite}
          viewMode={viewMode}
          setViewMode={setViewMode}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          onPreview={(a) =>
            playUrl(archetypePreviewUrl(a.id), a.id, a.name, archetypePreviewUrl(a.id, true))
          }
          onUse={(a) => materialize(a, useArchetypeAsProfile, 'studio')}
          onUseInStories={(a) => materialize(a, useArchetypeAsProfile, 'stories')}
          onUseAsAudiobookDefault={(a) => materialize(a, useArchetypeAsProfile, 'audiobook')}
          onDesign={openDesigner}
          materializingId={materializingId}
        />
      ) : zone === 'community' ? (
        <CommunityZone
          t={t}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          favorites={favorites}
          toggleFavorite={toggleFavorite}
          onPreview={(item) =>
            playUrl(
              communityPreviewUrl(item.id),
              communityPlaybackId(item),
              item.name,
              item.type === 'preset' ? communityPreviewUrl(item.id, true) : null,
            )
          }
          flash={flash}
          onDesign={openDesigner}
          onUse={(item) => materialize(item, addCommunityItem, 'studio')}
          onUseInStories={(item) => materialize(item, addCommunityItem, 'stories')}
          onUseAsAudiobookDefault={(item) => materialize(item, addCommunityItem, 'audiobook')}
          materializingId={materializingId}
        />
      ) : (
        <ImportsZone
          t={t}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          onPlayGallery={(v) => playUrl(previewVoiceUrl(v.id), v.id, v.name)}
          onUseProfile={placeProfile}
          flash={flash}
        />
      )}
    </div>
  );
}
